import base64
from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
import hashlib
import os
from totp import TOTP

app = Flask(__name__)
limiter = Limiter(get_remote_address, app=app, default_limits=[])

# Parameters for TOTP
time_interval_sec = 30
digit_num = 6
hash_alg = hashlib.sha1

# Store the user secrets
user_secrets = {}

@app.route("/register", methods=["POST"])
def register():
    """
    Add a new user. Register their username and initiate TOTP by generating
    and sending them a shared secret.
    """
    # Get the username
    username = request.json.get("username")
    if not username:
        return jsonify({"error": "Username required"}), 400
    if username in user_secrets:
        return jsonify({"error": "User already exists"}), 400

    # The number of the randomly generated bytes should be equal to the number
    # of bytes returned by the hash function used in HMAC as suggested in RFC
    # 2104
    random_bytes_size = hash_alg().digest_size

    # Generate the shared secret and store it with the username
    secret = base64.b32encode(os.urandom(random_bytes_size)).decode()
    user_secrets[username] = secret

    # Send a verification of successful user registration and the shared secret
    return jsonify({"message": "User registered", "username": username,
        "secret": secret})

@app.route("/login", methods=["POST"])
@limiter.limit("1 per 5 seconds")
def login():
    # Get the username
    username = request.json.get("username")
    if username not in user_secrets:
        return jsonify({"error": "User not found"}), 401

    # Assume that the password authentication was successful and move on to
    # TOTP verification

    # Create a TOTP object using the stored user secret
    totp_handle = TOTP(user_secrets[username],
            time_interval_sec=time_interval_sec, digit_num=digit_num,
            hash_alg=hash_alg)

    # Get the OTP that the user sent and verify it
    otp = request.json.get("otp")
    if totp_handle.verify_otp(otp, 1):
        return jsonify({"message": "Login successful"})
    else:
        return jsonify({"error": "Invalid OTP"}), 401


if __name__ == "__main__":
    app.run(debug=True)
